# Generated by Django 3.2.13 on 2023-01-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ask',
            new_name='Question',
        ),
        migrations.AddField(
            model_name='type',
            name='bad_match',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='type',
            name='dislike',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='type',
            name='good_match',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='type',
            name='like',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='type',
            name='personality',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='type',
            name='mbti',
            field=models.CharField(max_length=10),
        ),
    ]
