# Generated by Django 3.2.13 on 2023-01-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230126_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='question',
            name='alphabet',
        ),
    ]
