# Generated by Django 3.2.13 on 2023-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230129_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer1_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
